backend:
  name: git-gateway
  branch: master

media_folder: src/assets/images
public_folder: /images

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/pages/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/content/about.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/about"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/content/example.md"
        label: "Example"
        name: "example"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "example-page"}
          - {label: "Path", name: "path", widget: "hidden", default: "/example"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
