backend:
  name: github
  repo: huntercaron/boiled

media_folder: src/content/assets
public_folder: static/assets

collections:
  - name: posts
    label: Posts
    folder: src/content/posts
    create: true
    fields:
      - { name: templateKey, label: Template Key, widget: hidden, default: post}
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: pages
    label: Pages
    files:
      - name: about
        label: AboutPage
        file: src/content/about.md
        fields:
          - { name: templateKey, label: Template Key, widget: hidden, default: post}
          - { name: path, label: Path }
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title }
          - { name: subtitle, label: Subtitle }
          - { name: description, label: Description, widget: text }
          - { name: body, label: Body, widget: markdown }
          - label: Example List
            name: exampleList
            widget: list
            fields:
              - { name: listItem, label: List Item, widget: string }
