backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/pages/content/posts"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SubTitle", name: "subtitle", widget: "string"}
      - {label: "Path", name: "path", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "templateKey", name: "templateKey", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
